create table public.booking
(
    id                bigint generated by default as identity
        primary key,
    base_amount       numeric(38, 2),
    booking_reference varchar(255) not null
        constraint uk8mvnknrrkmlgc3w8creygru9o
            unique,
    booking_time      timestamp(6),
    discount_amount   numeric(38, 2),
    expiry_time       timestamp(6),
    final_amount      numeric(38, 2),
    show_id           bigint       not null,
    status            varchar(255) not null
        constraint booking_status_check
            check ((status)::text = ANY
                   ((ARRAY ['INITIATED_BOOKING'::character varying, 'PENDING_BOOKING'::character varying, 'CONFIRMED_BOOKING'::character varying, 'PENDING_PAYMENT'::character varying, 'CANCELLED_BOOKING'::character varying, 'EXPIRED_BOOKING'::character varying])::text[])),
    user_id           bigint       not null
);

alter table public.booking
    owner to kaizen;


create table public.booking_seat
(
    id                bigint generated by default as identity
        primary key,
    price             double precision,
    price_paid        double precision,
    seat_inventory_id bigint,
    booking_id        bigint
        constraint fk3gcy7w2me25kc4qp8nobmg4q6
            references public.booking
);

alter table public.booking_seat
    owner to kaizen;



create table public.outbox_events
(
    event_id       bigint generated by default as identity
        primary key,
    aggregate_id   varchar(255),
    aggregate_type varchar(255),
    created_at     timestamp(6),
    event_status   varchar(255)
        constraint outbox_events_event_status_check
            check ((event_status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'PROCESSED'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])),
    event_type     varchar(255),
    payload        jsonb,
    processed_at   timestamp(6),
    status         varchar(255)
);

alter table public.outbox_events
    owner to kaizen;



create table public.seat_inventory
(
    id          bigint generated by default as identity
        primary key,
    price       double precision,
    seat_number varchar(255),
    seat_status varchar(255)
        constraint seat_inventory_seat_status_check
            check ((seat_status)::text = ANY
                   ((ARRAY ['RESERVED'::character varying, 'AVAILABLE'::character varying, 'BOOKED'::character varying, 'CANCELLED'::character varying])::text[])),
    show_id     bigint
        constraint fksbglt8srw73xd5tkwrkbl4x21
            references public.show
);

alter table public.seat_inventory
    owner to kaizen;



create table public.show
(
    id              bigint generated by default as identity
        primary key,
    available_seats integer        not null,
    base_price      numeric(38, 2) not null,
    end_time        timestamp(6)   not null,
    movie_id        bigint         not null,
    show_time       timestamp(6)   not null,
    status          varchar(255)   not null,
    theatre_id      bigint         not null,
    total_seats     integer        not null
);

alter table public.show
    owner to kaizen;

